### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by pongoman** [ianaya89/vue-sticky-js#1]
`npm install vue-sticky-js` throws error. I have attached screenshots with the output and npm log.

![sticky-error2](https://cloud.githubusercontent.com/assets/14333747/21169187/c1171262-c1c2-11e6-90b8-452920864e61.png)
![sticky-error](https://cloud.githubusercontent.com/assets/14333747/21169188/c11b5b88-c1c2-11e6-817a-79c5bf640127.png)

[npm-debug.txt](https://github.com/ianaya89/vue-sticky-js/files/650768/npm-debug.txt)

**Comment by ianaya89** [comment]
Hey, thanks for your feedback.

The issue was related to an error in npm-scripts. I pushed the fix in latest version (v0.0.3).
Can you check it?

**Comment by pongoman** [comment]
Hi, now install works fine.
I believe the path to dist directory pointing to min.js is not correct in package.json
Will this be compatible with Vue 2?
Thanks

**Comment by ianaya89** [comment]
Thanks again, fixed now (v0.0.4). I didn't try it in `Vue 2` but I think should be compatible. Please let me know that, I can work in an upgrade/fix if not.

BTW, congrats for the book. Was really helpful for me to start learning Vue.

**Comment by pongoman** [comment]
Hi again, I tried with Vue 2 getting some errors, if I get any further with this, will let you know. I think you should close this and add that is not yet tested with Vue 2.

Thank you, happy to hear that you liked it. :blush:

**Comment by ianaya89** [comment]
Support for Vue 2 is still pending
